Api nova e correcao da antiga
cleiton-tavares/embromachion pull request #11
Opened 2022-04-27 13:11 UTC by marcelobc1

2022-04-27 18:09 UTC, cleiton-tavares requested changes

2022-04-27 18:09 UTC, cleiton-tavares commented on src/routes/opcredloans.js
> +  express.get(baseApi, (req, res) => IndexController.batchApi(model, '', req, res));
Essa rota esta conflitando com a Single API (Linha 15)

2022-04-27 18:09 UTC, cleiton-tavares commented on src/routes/opcredloans.js
> +  express.get(baseApi, (req, res) => IndexController.sigleApi(model, '', req, res));
Essa rota está conflitando com a rota batch (linha 22)

2022-04-27 18:22 UTC, marcelobc1 reviewed
Corrigido

2022-04-27 18:24 UTC, marcelobc1 reviewed
Corrigido nesse commit

2022-04-28 12:11 UTC, cleiton-tavares commented
@marcelobc1 conflito no arquivo src/routes/opcredoverdraft.js

2022-05-02 17:16 UTC, closed without merging